In [152]:
import numpy as np
import random

In [153]:
name = "sio2.dat"
file_o = open(name,"w")
a = 35.1
pcharge = 2.4
ncharge = -1.2
for i in range(1,1001):
    file_o.write('{} 1 {} {} {} {}\n'.format(i, pcharge, a*np.random.uniform(0,1), a*np.random.uniform(0,1), a*np.random.uniform(0,1) )) 
    
for i in range(1001,3001):
    file_o.write('{} 2 {} {} {} {}\n '.format(i, ncharge, a*np.random.uniform(0,1), a*np.random.uniform(0,1), a*np.random.uniform(0,1) ))        
    
file_o.close()  
print("Done!")

Done!


In [154]:
# The second format: SiO2.xyz
name = "SiO2.xyz"
file_o = open(name,"w")
a = 35.1
file_o.write('3000\n')
file_o.write('i = 0, time = 0.000 E = 0.000\n')
for i in range(1,1001):
    file_o.write('Si {} {} {}\n'.format(a*np.random.uniform(0,1), a*np.random.uniform(0,1), a*np.random.uniform(0,1) )) 
    
for i in range(1001,3001):
    file_o.write('O {} {} {}\n '.format(a*np.random.uniform(0,1), a*np.random.uniform(0,1), a*np.random.uniform(0,1) ))        
    
file_o.close()  
print("Done!")

Done!


In [155]:
a = 35.1
num_si = 1000
num_o = 2000
pcharge = 2.4
ncharge = -1.2
num = num_si + num_o
pos_si = a * np.random.uniform(0,1,3*num_si).reshape(3,num_si)
pos_o = a * np.random.uniform(0,1,3*num_o).reshape(3,num_o)


name = "SiO2_.dat"
file_o = open(name,"w")

for i in range(num_si):
    file_o.write('{} 1 {} {} {} {}\n'.format(i+1, pcharge, pos_si[0][i], pos_si[1][i],pos_si[2][i] )) 
    
for i in range(num_o):
    file_o.write('{} 2 {} {} {} {}\n '.format(num_si+i+1, ncharge, pos_o[0][i],pos_o[1][i],pos_o[2][i] ))        
file_o.close()  
print("Done!")

Done!


In [156]:
# The second format: SiO2_.xyz
# With 3D array.
a = 35.1
num_si = 1000
num_o = 2000
num = num_si + num_o
pos_si = a * np.random.uniform(0,1,3*num_si).reshape(3,num_si)
pos_o = a * np.random.uniform(0,1,3*num_o).reshape(3,num_o)

name = "SiO2_.xyz"
file_o = open(name,"w")
file_o.write('3000\n')
file_o.write('i = 0, time = 0.000 E = 0.000\n')

for i in range(num_si):
    file_o.write('Si {} {} {}\n'.format(pos_si[0][i], pos_si[1][i],pos_si[2][i] )) 
    
for i in range(num_o):
    file_o.write('O {} {} {}\n '.format(pos_o[0][i],pos_o[1][i],pos_o[2][i] ))        
file_o.close() 

print("Done!")

Done!


# 2 Generating fully random coordinates is not a good idea?

If we just randomly generate the intial configuration. Because the atoms may overlap, there may be error. To avoid this problem, now, we divide the simulation box into many domains, and put one atom randomly into each domain.

In [157]:
import math

gap = 2 
a = 35.1 / gap
b = a
c = a
num_si = 1000
num_o = 2000

arr_a = np.array(range(math.floor(a)))
arr_b = np.array(range(math.floor(b)))
arr_c = np.array(range(math.floor(c)))
print(arr_a)
print(arr_b)
print(arr_c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [158]:
grids = [[gap*a0, gap*b0, gap*c0] for a0 in arr_a for b0 in arr_b for c0 in arr_c]

# Shuffle is very important step, because we do not want put all Si atoms or Oxygen atoms together. 
random.shuffle(grids)

name = "sio2_grid.dat"
file_o = open(name,"w")

for i in range(num_si):
    coord = grids.pop() # To avoid that two atoms take the same cell, we use pop(), which make sure that there is only one atom in any cell.
    file_o.write('{} 1 {} {} {} {}\n'.format(i+1, pcharge, coord[0], coord[1], coord[2] )) 
    
for i in range(num_si,num_o+num_si):
    coord = grids.pop() 
    file_o.write('{} 2 {} {} {} {}\n '.format(i+1, ncharge, coord[0], coord[1], coord[2] ))        
file_o.close()  
print("Done!")

Done!


In [159]:
# Generate .xyz format coordinates.

grids = [[gap*a0, gap*b0, gap*c0] for a0 in arr_a for b0 in arr_b for c0 in arr_c]

# Shuffle is very important step, because we do not want put all Si atoms or Oxygen atoms together. 
random.shuffle(grids)

name = "sio2_grid.xyz"
file_o = open(name,"w")
file_o.write('3000\n')
file_o.write('i = 0, time = 0.000 E = 0.000\n')

for i in range(num_si):
    coord = grids.pop() # To avoid that two atoms take the same cell, we use pop(), which make sure that there is only one atom in any cell.
    file_o.write('Si {} {} {}\n'.format(coord[0], coord[1], coord[2])) 
    
for i in range(num_si, num_o+num_si):
    coord = grids.pop()
    file_o.write('O {} {} {}\n '.format(coord[0], coord[1], coord[2]))        
file_o.close() 

print("Done!")

Done!


In [160]:
# The total number of sites
35 * 35 * 35

42875

In [161]:
17 * 17 * 17

4913